TEX := las_granadas \
         biographie \
         introduction \
         l_amateur_de_poemes \
         feerie \
         meme_feerie \
         au_bois_dormant \
         le_bois_amical \
         un_feu_distinct \
         vue \
         l_abeille \
         les_pas \
         la_ceinture \
         le_sylphe \
         l_insinuant \
         les_grenades \
         le_vin_perdu \
         interieur \
         colloque \
         insinuant_II \
         la_caresse

