TEX := patchwork \
         cancion_de_carnaval \
         mia \
         dice_mia \
         syrinx \
         callar \
         elegia_de_atarazanas \
         la_novela_de_una_tienda \
         cantico
